allconfig={
    "Cora":{
            'embed_dim': 8,
            'hid_dim_node': 64,
            'num_layers_node_encoder': 2,
            'num_layers_node_decoder': 1,
            "dropout_node": 0,
            "alpha_adj": 0.3,
            "adj_fuse": True,
            "topk": None,
            "epsilon": 0.1,
            "num_pers_cos": 8,
            "weightedcosine": False,
            "hid_dim_encode": 32,
            "num_layers_encoder": 2,
            "temperature": 0.5,
            "loss_con": 10,
            "tau": 0.5,
            "K":10,
        },
    "CiteSeer":{
            'embed_dim': 8,
            'hid_dim_node': 64,
            'num_layers_node_encoder': 2,
            'num_layers_node_decoder': 1,
            "dropout_node": 0,
            "alpha_adj": 0.4,
            "adj_fuse": True,
            "topk": 1,
            "epsilon": 0.2,
            "num_pers_cos": 8,
            "weightedcosine": True,
            "hid_dim_encode": 32,
            "num_layers_encoder": 2,
            "temperature": 0.5,
            "loss_con": 1.8,
            "tau": 0.5,
            "K":10
        },
    "PubMed":{
            'embed_dim': 8,
            'hid_dim_node': 64,
            'num_layers_node_encoder': 2,
            'num_layers_node_decoder': 1,
            "dropout_node": 0,
            "alpha_adj": 0.8, #0.4 0.2 0.1
            "adj_fuse": True,
            "topk": None,
            "epsilon": 0.2,
            "num_pers_cos": 16,
            "weightedcosine": True,
            "hid_dim_encode": 32,
            "num_layers_encoder": 2,
            "temperature": 0.5,
            "loss_con": 2.5,
            "tau": 0.5,
            "K":50
        },
    "Computers":{
            'embed_dim': 8,
            'hid_dim_node': 64,
            'num_layers_node_encoder': 2,
            'num_layers_node_decoder': 1,
            "dropout_node": 0,
            "alpha_adj": 1, #0.4 0.2 0.1
            "adj_fuse": True,
            "topk": 30,
            "epsilon": 0.2,
            "num_pers_cos": 16,
            "weightedcosine": True,
            "hid_dim_encode": 32,
            "num_layers_encoder": 2,
            "temperature": 0.5,
            "loss_con": 3,
            "tau": 0.5,
            "K":10
        },
    "Photo":{
            'embed_dim': 8,
            'hid_dim_node': 64,
            'num_layers_node_encoder': 2,
            'num_layers_node_decoder': 1,
            "dropout_node": 0,
            "alpha_adj": 0.8, #0.4 0.2 0.1
            "adj_fuse": True,
            "topk": 30,
            "epsilon": 0.2,
            "num_pers_cos": 16,
            "weightedcosine": True,
            "hid_dim_encode": 32,
            "num_layers_encoder": 2,
            "temperature": 1.5,
            "loss_con": 1,
            "tau": 0.5,
            "K":30
        },
    "CS": {
        'embed_dim': 8,
        'hid_dim_node': 64,
        'num_layers_node_encoder': 2,
        'num_layers_node_decoder': 1,
        "dropout_node": 0,
        "alpha_adj": 1,
        "adj_fuse": True,
        "topk": 40,
        "epsilon": 0.2,
        "num_pers_cos": 16,
        "weightedcosine": True,
        "hid_dim_encode": 32,
        "num_layers_encoder": 2,
        "temperature": 0.5,
        "loss_con": 2,
        "tau": 0.5,
        "K": 30
    },
    "Physics": {
        'embed_dim': 8,
        'hid_dim_node': 64,
        'num_layers_node_encoder': 2,
        'num_layers_node_decoder': 1,
        "dropout_node": 0.1,
        "alpha_adj": 0.4,
        "adj_fuse": True,
        "topk": 30,
        "epsilon": 0.2,
        "num_pers_cos": 8,
        "weightedcosine": True,
        "hid_dim_encode": 32,
        "num_layers_encoder": 2,
        "temperature": 0.5,
        "loss_con": 1.8,
        "tau": 0.5,
        "K": 10
    },
    "ogbn-arxiv": {
        'embed_dim': 8,
        'hid_dim_node': 64,
        'num_layers_node_encoder': 2,
        'num_layers_node_decoder': 1,
        "dropout_node": 0.1,
        "alpha_adj": 0.4,
        "adj_fuse": True,
        "topk": 30,
        "epsilon": 0.1,
        "num_pers_cos": 8,
        "weightedcosine": True,
        "node_gen_lr": 0.01,
        "node_gen_weight_decay": 5e-4,
        "hid_dim_encode": 32,
        "num_layers_encoder": 2,
        "temperature": 0.5,
        "loss_con": 1.8,
        "tau": 0.5,
        "K": 20
    },
    "Roman-empire": {
        'embed_dim': 8,
        'hid_dim_node': 64,
        'num_layers_node_encoder': 2,
        'num_layers_node_decoder': 1,
        "dropout_node": 0.1,
        "alpha_adj": 2,
        "adj_fuse": True,
        "topk": 30,
        "epsilon": 0.1,
        "num_pers_cos": 16,
        "weightedcosine": True,
        "hid_dim_encode": 32,
        "num_layers_encoder": 2,
        "temperature": 0.5,
        "loss_con": 2,
        "tau": 0.5,
        "K": 10
    },
    "Amazon-ratings": {
        'embed_dim': 8,
        'hid_dim_node': 64,
        'num_layers_node_encoder': 2,
        'num_layers_node_decoder': 1,
        "dropout_node": 0.1,
        "alpha_adj": 0.5,
        "adj_fuse": True,
        "topk": 30,
        "epsilon": 0.1,
        "num_pers_cos": 16,
        "weightedcosine": True,
        "hid_dim_encode": 32,
        "num_layers_encoder": 2,
        "temperature": 0.5,
        "loss_con": 1,
        "tau": 0.5,
        "K": 30
    },
    "Tolokers": {
        'embed_dim': 8,
        'hid_dim_node': 64,
        'num_layers_node_encoder': 2,
        'num_layers_node_decoder': 1,
        "dropout_node": 0.1,
        "alpha_adj": 1,
        "adj_fuse": True,
        "topk": 30,
        "epsilon": 0.1,
        "num_pers_cos": 16,
        "weightedcosine": True,
        "hid_dim_encode": 32,
        "num_layers_encoder": 2,
        "temperature": 0.5,
        "loss_con": 1,
        "tau": 0.5,
        "K": 10
    },
}